const assert=require('node:assert/strict');
module.exports=async function testCreation({page,data,control,tab,artifactDir,results}) {
  await page.evaluate(() => sessionStorage.setItem('immuvi:qa:entgcnlfsnysnwyadzzp:clickup:11111111-1111-4111-8111-111111111111','synthetic-clickup-key'));
  await tab(page,'Creative Matrix');
  await page.locator('[data-matrix-cell]').first().click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('tab',{name:'+ Add Creative'}).click();
  await dialog.getByRole('button',{name:'Blank Brief',exact:true}).click();
  await dialog.getByLabel('Brief name').fill('Workflow acceptance brief');
  await dialog.getByLabel('Creative hypothesis',{exact:true}).fill('Preserve this hypothesis');
  await dialog.getByText('Additional notes',{exact:true}).click();
  await dialog.getByLabel('Brief notes',{exact:true}).fill('Preserve this full brief');
  await dialog.getByLabel('Push to Action Plan now',{exact:true}).uncheck();
  await dialog.getByRole('button',{name:'Create brief',exact:true}).click();
  await dialog.getByLabel('Matrix due date for Workflow acceptance brief').fill('2026-10-12');
  await dialog.getByRole('button',{name:'Add Workflow acceptance brief to Action Plan',exact:true}).click();
  await dialog.getByText('Creative added to Action Plan.',{exact:true}).waitFor();
  assert.equal(await dialog.getByRole('button',{name:'Add Workflow acceptance brief to Action Plan',exact:true}).isDisabled(),true);
  const ad=data.ads.find((ad) => ad.format_name==='Workflow acceptance brief');
  assert.equal(data.manual_actions.filter((a) => a.payload.sourceAdId===ad.id).length,1);
  await dialog.getByRole('button',{name:'Close inspector'}).click();
  await page.waitForFunction(() => document.querySelector('[data-plan-tab-count] > span')?.textContent === '2');
  await tab(page,'Action Plan');
  await page.getByRole('button',{name:'Cards view',exact:true}).click();
  const row=page.locator('article').filter({has:page.getByRole('button',{name:'Push to ClickUp: Workflow acceptance brief',exact:true})});
  assert.equal(await page.getByLabel('Due date for Workflow acceptance brief',{exact:true}).inputValue(),'2026-10-12');
  await row.getByText('Preserve this full brief',{exact:true}).waitFor();
  control.creationFailure=true;
  await page.getByRole('button',{name:'Push to ClickUp: Workflow acceptance brief',exact:true}).click();
  await page.getByText('ClickUp may have created the task. Use Recover ClickUp link.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Recover ClickUp link for Workflow acceptance brief',exact:true}).waitFor();
  assert.equal(control.creationPosts,1);
  await page.reload({waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Recover ClickUp link for Workflow acceptance brief',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Status for Workflow acceptance brief',{exact:true}).isDisabled(),true);
  assert.equal(await page.getByLabel('Due date for Workflow acceptance brief',{exact:true}).isDisabled(),true);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:`${artifactDir}/creation-recovery-mobile.png`,fullPage:true});
  await page.getByRole('button',{name:'Recover ClickUp link for Workflow acceptance brief',exact:true}).click();
  await page.getByText('Linked to ClickUp task qa-created-task.',{exact:true}).waitFor();
  assert.equal(control.creationPosts,1);
  assert.equal(data.manual_actions.filter((a) => a.payload.sourceAdId===ad.id).length,1);
  await page.locator('a[href="https://app.clickup.com/t/qa-created-task"]').first().waitFor();
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.getByRole('button',{name:'Push to ClickUp: Workflow acceptance brief',exact:true}).count(),0);
  await page.getByLabel('Status for Workflow acceptance brief',{exact:true}).selectOption('Testing');
  await page.getByText('Task successfully updated.',{exact:true}).waitFor();
  await page.getByLabel('Due date for Workflow acceptance brief',{exact:true}).fill('2026-10-14');
  await page.getByText('Task successfully updated.',{exact:true}).waitFor();
  await tab(page,'Creative Matrix');await page.locator('[data-matrix-cell]').first().click();
  await dialog.locator('a[href="https://app.clickup.com/t/qa-created-task"]').waitFor();
  assert.equal(await dialog.getByLabel('Matrix due date for Workflow acceptance brief').inputValue(),'2026-10-14');
  await dialog.getByRole('button',{name:'Close inspector'}).click();
  await page.setViewportSize({width:1440,height:1000});await tab(page,'Action Plan');
  await page.locator('a[href="https://app.clickup.com/t/qa-created-task"]').first().waitFor();
  await page.screenshot({path:`${artifactDir}/creation-linked-desktop.png`,fullPage:true});
  assert.equal(new URL(page.url()).pathname,'/');
  results.push('Matrix to Action Plan staging, retained brief/due date, uncertain create across reload, guarded edits, recovery without duplicate task, stable links and mobile layout');
};
