const assert=require('node:assert/strict');
module.exports=async function testMatrix({page,data,emit,tab,artifactDir,results}) {
  const stamp=new Date().toISOString(), today=new Date().toLocaleDateString('en-CA');
  data.angles.push({id:'ANG-2',product_id:'qa-fixture',name:'Health',status:'Winner',created_at:stamp,updated_at:stamp});
  data.ads.push({...data.ads[0],id:'OLD',format_name:'Older winner',status:'Mild Winner',created_at:'2025-01-01T12:00:00Z'});
  data.inspirations.push({id:'INS-1',product_id:'qa-fixture',title:'Classified inspiration',status:'Classified',url:'https://example.test/ad',data:{adType:'Photo',funnelStage:'MOF'},updated_at:stamp},
    {id:'INS-PENDING',product_id:'qa-fixture',title:'Pending inspiration',status:'Queued',data:{adType:'Video'},updated_at:stamp});
  await tab(page,'Creative Matrix');
  await page.getByRole('button',{name:'Energy x Busy people: 2 creatives',exact:true}).waitFor();
  await page.getByLabel('Matrix date range').selectOption('custom');
  await page.getByLabel('Matrix date from').fill(today); await page.getByLabel('Matrix date to').fill(today);
  await page.getByRole('button',{name:'Energy x Busy people: 1 creatives',exact:true}).waitFor();
  await page.getByRole('button',{name:'Lifetime',exact:true}).click();
  await page.getByRole('button',{name:'Energy x Busy people: 2 creatives',exact:true}).waitFor();
  await page.getByLabel('Matrix sort').selectOption('nameDesc');
  assert.equal(await page.locator('[data-angle-id]').first().getAttribute('data-angle-id'),'ANG-2');
  await page.getByLabel('Matrix sort').selectOption('manual');
  await page.getByRole('button',{name:'Move Health up'}).click();
  assert.equal(await page.locator('[data-angle-id]').first().getAttribute('data-angle-id'),'ANG-2');
  await page.getByRole('button',{name:'compact density'}).click();
  assert.equal(await page.locator('table[data-density]').getAttribute('data-density'),'compact');
  await page.reload({waitUntil:'networkidle'});
  await page.locator('table[data-density="compact"]').waitFor();
  assert.equal(await page.locator('[data-angle-id]').first().getAttribute('data-angle-id'),'ANG-2');
  await page.getByRole('button',{name:'Reset Matrix filters'}).click();
  await page.getByRole('button',{name:'Health x Busy people: 0 creatives',exact:true}).click();
  const dialog=page.getByRole('dialog');
  assert.equal(await page.evaluate(() => document.body.style.overflow),'hidden');
  await dialog.getByRole('tab',{name:'+ Add Creative',exact:true}).click();
  await dialog.getByLabel('Select QA creative',{exact:true}).check();
  const scroll=await page.evaluate(() => scrollY);
  emit('ads','UPDATE',data.ads[0]); await page.waitForTimeout(250);
  assert.equal(await dialog.getByLabel('Select QA creative',{exact:true}).isChecked(),true);
  await page.mouse.wheel(0,300);assert.equal(await page.evaluate(() => scrollY),scroll);
  await dialog.getByRole('button',{name:'Add 1 selected',exact:true}).click();
  await dialog.locator('[data-cell-creative]').getByLabel('Task name for QF-001-QA creative',{exact:true}).waitFor();
  assert.equal(data.ads.find((a) => a.format_name==='QF-001-QA creative').drive_link,'');
  await dialog.getByRole('tab',{name:'+ Add Creative',exact:true}).click();
  await dialog.getByRole('button',{name:'From Inspiration',exact:true}).click();
  assert.equal(await dialog.getByLabel('Select Pending inspiration').isDisabled(),true);
  await dialog.getByLabel('Select Classified inspiration').check();
  await dialog.getByRole('button',{name:'Add 1 selected',exact:true}).click();
  await dialog.getByRole('button',{name:'Edit QF-002-INS-1',exact:true}).waitFor();
  await dialog.getByRole('tab',{name:'+ Add Creative',exact:true}).click();
  await dialog.getByRole('button',{name:'Blank Brief',exact:true}).click();
  await dialog.getByLabel('Brief name').fill('New matrix brief');
  await dialog.getByLabel('Creative hypothesis',{exact:true}).fill('Cell-specific hypothesis');
  await dialog.getByRole('button',{name:'Create brief',exact:true}).click();
  await dialog.getByRole('button',{name:'Edit New matrix brief',exact:true}).click();
  await dialog.getByLabel('Notes',{exact:true}).fill('Saved Matrix edit');
  await dialog.getByRole('button',{name:'Save creative',exact:true}).click();
  await dialog.getByLabel('Matrix status for New matrix brief').selectOption('Winner');
  await dialog.getByRole('button',{name:'Spawn from New matrix brief'}).click();
  await dialog.getByRole('button',{name:'Create 1 variations'}).click();
  await dialog.getByRole('button',{name:'Edit New matrix brief - V1',exact:true}).waitFor();
  await dialog.getByRole('button',{name:'Remove New matrix brief from cell',exact:true}).click();
  await dialog.getByRole('button',{name:'Edit New matrix brief',exact:true}).waitFor({state:'detached'});
  await dialog.locator('summary').filter({hasText:'Removed from cell'}).click();
  await dialog.getByRole('button',{name:'Restore New matrix brief',exact:true}).click();
  await dialog.getByRole('button',{name:'Edit New matrix brief',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await dialog.evaluate((el) => el.scrollWidth<=el.clientWidth),true);
  assert.equal(await dialog.locator('input[type=date]').evaluateAll((inputs) => inputs.every((input) => {
    const field=input.getBoundingClientRect(),parent=input.parentElement.getBoundingClientRect();
    return field.left>=parent.left && field.right<=parent.right+1;
  })),true,'Due dates must fit inside their field labels');
  await page.screenshot({path:`${artifactDir}/matrix-dialog-mobile.png`});
  await dialog.getByRole('button',{name:'Close inspector'}).click();
  assert.equal(await page.evaluate(() => document.body.style.overflow),'');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:`${artifactDir}/matrix-mobile.png`,fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'detailed density'}).click();
  await page.screenshot({path:`${artifactDir}/matrix-desktop.png`,fullPage:true});
  await page.reload({waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Health x Busy people: 4 creatives',exact:true}).waitFor();
  assert.equal(new URL(page.url()).pathname,'/');
  results.push('Matrix date scope/highlight, persisted sort/density/manual order, source selection without scroll/draft loss, Tracker/Inspiration/blank creation, editing, variations, unlink/restore, reload and mobile layout at /');
};
