const assert = require('node:assert/strict');
module.exports = async function testProduction({page,context,data,control,emit,tab,artifactDir,results}) {
  const product='qa-fixture', stamp=data.manual_actions[0].updated_at;
  const standalone=(id,status='Untested')=>({id,product_id:product,live_status:status,payload:{title:id},created_at:stamp,updated_at:stamp});
  const action=data.manual_actions[0], ad=data.ads[0];
  ad.meta={dueDate:'2026-10-12',driveLink:'javascript:alert(1)'};action.payload.dueDate='2026-01-01';
  data.manual_actions.push(...Array.from({length:501},(_,i)=>standalone(`PAGE-${i}`)),standalone('Mild result','Mild Winner'),standalone('Killed result','Killed'));
  data.ads.push({...ad,id:'GONE',deleted_at:stamp},{...ad,id:'QUARANTINE',meta:{_productBoundaryQuarantined:true}});
  for(const id of ['GONE','QUARANTINE','TOMBSTONE'])data.manual_actions.push({...standalone(`ACTION-${id}`),payload:{title:`Hidden ${id}`,adId:id}});
  data.deleted_ads.push({id:'TOMBSTONE',product_id:product});
  const readPages=[];let edits=0;
  await context.route(/\/rest\/v1\/manual_actions\?/,async(route)=>{readPages.push(new URL(route.request().url()).searchParams.get('offset'));await route.fallback();});
  await context.route(/\/rest\/v1\/rpc\/qa_plan_(edit|batch)$/,async(route)=>{edits++;await route.fallback();});
  await tab(page,'Production');
  const card=(id)=>page.locator(`[data-production-task="${id}"]`);
  const column=(id)=>page.locator(`[data-production-column="${id}"]`);
  await card('PAGE-500').waitFor();assert.ok(readPages.includes('500'));
  for(const id of ['GONE','QUARANTINE','TOMBSTONE'])assert.equal(await card(`ACTION-${id}`).count(),0);
  assert.equal(await column('done').locator('[data-production-task]').count(),2);
  assert.ok((await card('ACTION-1').innerText()).includes('2026-10-12'));
  assert.equal(await card('ACTION-1').getByRole('link',{name:'Drive',exact:true}).count(),0);
  assert.equal(edits,0,'Read/pagination must not write');
  data.manual_actions=data.manual_actions.filter((row)=>!row.id.startsWith('PAGE-') || row.id==='PAGE-0');emit('manual_actions','DELETE',{id:'PAGE-1'});
  await card('PAGE-500').waitFor({state:'hidden'});

  const status=page.getByLabel('Status for QA creative',{exact:true});
  await page.getByRole('button',{name:'Task controls for QA creative',exact:true}).click();
  await status.selectOption('Testing');await page.getByRole('status').filter({hasText:'Status changed to Testing.'}).waitFor();
  await status.selectOption('Winner');await page.getByRole('status').filter({hasText:'Status changed to Winner.'}).waitFor();
  assert.equal(ad.status,'Winner');
  const before=edits;
  await card('ACTION-1').locator('strong').dragTo(column('done'));assert.equal(edits,before,'Same-column drag is a no-op');
  await card('ACTION-1').locator('strong').dragTo(column('queue'));await page.getByRole('status').filter({hasText:'Status changed to Untested.'}).waitFor();
  assert.equal(ad.status,'Untested');

  // Keep the drag-start version even if a realtime refresh changes the visible card.
  const transfer=await page.evaluateHandle(()=>new DataTransfer());
  await card('ACTION-1').dispatchEvent('dragstart',{dataTransfer:transfer});
  ad.status='Winner';ad.updated_at=new Date(Date.parse(ad.updated_at)+1000).toISOString();emit('ads','UPDATE',ad);
  await page.waitForFunction(()=>document.querySelector('select[aria-label="Status for QA creative"]')?.value==='Winner');
  control.expectedWorkflowRejections=1;
  await column('progress').dispatchEvent('drop',{dataTransfer:transfer});
  await page.getByRole('alert').filter({hasText:'Task changed'}).waitFor();assert.equal(ad.status,'Winner');
  await transfer.dispose();
  await page.getByRole('button',{name:'Refresh',exact:true}).click();
  await status.selectOption('Testing');await page.getByRole('status').filter({hasText:'Status changed to Testing.'}).waitFor();

  const openDue=()=>page.getByRole('button',{name:'Edit due date for QA creative',exact:true}).click();
  await openDue();let dialog=page.getByRole('dialog',{name:'Due date: QA creative',exact:true});
  await dialog.getByLabel('Due date',{exact:true}).fill('2026-11-15');
  ad.updated_at=new Date(Date.parse(ad.updated_at)+1000).toISOString();ad.meta.dueDate='2026-11-01';emit('ads','UPDATE',ad);
  await page.waitForFunction(()=>document.querySelector('[data-production-task="ACTION-1"]')?.textContent.includes('2026-11-01'));
  assert.equal(await dialog.getByLabel('Due date',{exact:true}).inputValue(),'2026-11-15');
  control.expectedWorkflowRejections=1;
  await dialog.getByRole('button',{name:'Save due date',exact:true}).click();
  await dialog.getByRole('alert').filter({hasText:'Task changed'}).waitFor();assert.equal(ad.meta.dueDate,'2026-11-01');
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
  await openDue();await dialog.getByLabel('Due date',{exact:true}).fill('2026-11-15');
  await dialog.getByRole('button',{name:'Save due date',exact:true}).click();await dialog.waitFor({state:'hidden'});
  assert.equal(ad.meta.dueDate,'2026-11-15');
  await openDue();await dialog.getByRole('button',{name:'Clear date',exact:true}).click();
  await dialog.getByRole('button',{name:'Save due date',exact:true}).click();await dialog.waitFor({state:'hidden'});
  assert.equal(ad.meta.dueDate,'');
  await page.getByRole('button',{name:'Task controls for PAGE-0',exact:true}).click();
  await page.getByLabel('Status for PAGE-0',{exact:true}).selectOption('In Production');
  await page.getByRole('status').filter({hasText:'Status changed to In Production.'}).waitFor();
  assert.equal(data.manual_actions.find((row)=>row.id==='PAGE-0').live_status,'In Production');
  await page.getByRole('button',{name:'Edit due date for PAGE-0',exact:true}).click();
  const solo=page.getByRole('dialog',{name:'Due date: PAGE-0',exact:true});
  await solo.getByLabel('Due date',{exact:true}).fill('2026-12-01');
  await solo.getByRole('button',{name:'Save due date',exact:true}).click();await solo.waitFor({state:'hidden'});

  const reject=async(route)=>route.fulfill({status:200,contentType:'application/json',body:'null'});
  await context.route(/\/rest\/v1\/rpc\/qa_plan_edit$/,reject);
  await status.selectOption('Winner');await page.getByRole('alert').filter({hasText:'Save could not be verified'}).waitFor();
  assert.equal(await status.inputValue(),'Testing');assert.equal(control.clickupCalls.length,0);
  await context.unroute(/\/rest\/v1\/rpc\/qa_plan_edit$/,reject);
  await page.reload({waitUntil:'networkidle'});await tab(page,'Production');
  assert.ok((await card('PAGE-0').innerText()).includes('2026-12-01'));
  await openDue();await dialog.getByLabel('Due date',{exact:true}).fill('2026-12-31');
  data.deleted_ads.push({id:'AD-1',product_id:product});emit('deleted_ads','INSERT',{id:'AD-1',product_id:product});
  await card('ACTION-1').waitFor({state:'hidden'});
  const beforeDelete=edits;
  await dialog.getByRole('button',{name:'Save due date',exact:true}).click();
  await dialog.getByRole('alert').filter({hasText:'no longer available'}).waitFor();assert.equal(edits,beforeDelete);
  assert.equal(await dialog.getByLabel('Due date',{exact:true}).inputValue(),'2026-12-31');
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();

  for(const width of [320,390,768,1440]){
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:`${artifactDir}/production-board-${width}.png`});
    await page.getByRole('button',{name:'Edit due date for PAGE-0',exact:true}).click();
    assert.equal(await solo.evaluate((el)=>el.scrollWidth<=el.clientWidth && el.getBoundingClientRect().right<=innerWidth),true);
    await page.screenshot({path:`${artifactDir}/production-due-${width}.png`});
    await solo.getByRole('button',{name:'Cancel',exact:true}).click();
  }
  assert.equal(new URL(page.url()).pathname,'/');
  let fail=true;
  const failRead=async(route)=>fail?route.fulfill({status:200,contentType:'application/json',body:'null'}):route.fallback();
  await context.route(/\/rest\/v1\/manual_actions\?/,failRead);
  await page.getByRole('button',{name:'Refresh',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Incomplete manual_actions response'}).waitFor();
  assert.equal(await card('PAGE-0').count(),1);
  fail=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Incomplete manual_actions response'}).waitFor({state:'hidden'});
  data.manual_actions.push({...standalone('OTHER-PRODUCT'),product_id:'qa-second'});
  control.holdNextAds=true;emit('ads','UPDATE',ad);
  for(let attempt=0;!control.release && attempt<100;attempt++)await new Promise((resolve)=>setTimeout(resolve,10));
  assert.equal(typeof control.release,'function');
  await page.locator('main > section').first().locator('select').selectOption('qa-second');
  await card('OTHER-PRODUCT').waitFor();control.release();control.release=null;
  await page.waitForLoadState('networkidle');assert.equal(await card('PAGE-0').count(),0);
  fail=true;await page.locator('main > section').first().locator('select').selectOption(product);
  await page.getByRole('alert').filter({hasText:'Incomplete manual_actions response'}).waitFor();
  assert.equal(await page.locator('[data-production-task]').count(),0);
  assert.equal(await page.getByText('No production tasks.',{exact:true}).count(),0,'Initial failure is not an empty success');
  fail=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await card('PAGE-0').waitFor();
  data.manual_actions=[];emit('manual_actions','DELETE',{id:'PAGE-0'});
  await card('PAGE-0').waitFor({state:'hidden'});assert.equal(await page.getByText('No production tasks.',{exact:true}).count(),3);
  results.push('Production board: complete pagination, resolved due dates, deletion/quarantine/tombstones, safe links, consecutive versioned saves, same-column no-op and stale drag protection, linked/standalone date save/clear, retained stale/deleted drafts, unverified acknowledgement denial, reload and 320/390/768/1440px layouts; no external calls');
};
