const assert = require('node:assert/strict');
module.exports = async function testTracker({ page, data, emit, tab, artifactDir, results }) {
  await page.locator('details summary').click();
  await page.getByLabel('QA session API key').fill('synthetic-clickup-key');
  await page.getByText('ClickUp: QA ClickUp User', { exact: true }).waitFor();
  await tab(page, 'Creative Tracker');
  await page.getByRole('button', { name: 'Add creative', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Creative name', { exact: true }).fill('New tracker creative');
  await dialog.getByLabel('Angle', { exact: true }).selectOption('Energy');
  await dialog.getByLabel('Persona', { exact: true }).selectOption('Busy people');
  await dialog.getByLabel('Creative hypothesis').fill('A new approach');
  await dialog.getByRole('button', { name: 'Save creative', exact: true }).click();
  await dialog.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Edit New tracker creative', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Creative name', { exact: true }).fill('Unsaved draft');
  data.ads.find((ad) => ad.format_name === 'New tracker creative').meta.notes = 'Remote notes';
  emit('ads','UPDATE',data.ads.find((ad) => ad.format_name === 'New tracker creative'));
  await page.waitForTimeout(350);
  assert.equal(await dialog.getByLabel('Creative name', { exact: true }).inputValue(), 'Unsaved draft');
  await dialog.getByLabel('Creative name', { exact: true }).fill('Edited tracker creative');
  await dialog.locator('summary').click();
  await dialog.getByRole('button', { name: 'Load ClickUp fields' }).click();
  await dialog.getByLabel('Approved flag').check();
  await dialog.getByLabel('Score custom field', { exact: true }).fill('0');
  await dialog.getByLabel('Notes', { exact: true }).fill('Test notes');
  await page.screenshot({ path: `${artifactDir}/tracker-editor-desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${artifactDir}/tracker-editor-mobile.png`, fullPage: true });
  assert.equal(await dialog.evaluate((el) => el.scrollWidth <= el.clientWidth), true, 'Editor overflows on mobile');
  await dialog.getByRole('button', { name: 'Save creative', exact: true }).click();
  await dialog.waitFor({ state: 'detached' });
  const created = data.ads.find((ad) => ad.format_name === 'Edited tracker creative');
  assert.equal(created.meta._customFieldsRaw.score, 0);
  assert.equal(created.meta._customFieldsRaw['approved flag'], true);
  assert.equal(new URL(page.url()).pathname, '/');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Tracker overflows on mobile');
  await page.getByLabel('Status for Edited tracker creative', { exact: true }).selectOption('Winner');
  await page.getByRole('button', { name: 'Winning files for Edited tracker creative' }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Winning file URL').fill('https://drive.google.com/file/d/synthetic-file/view');
  await dialog.getByLabel('File name', { exact: true }).fill('Winning output');
  await dialog.getByRole('button', { name: 'Save winning file' }).click();
  await dialog.getByRole('button', { name: 'Remove Winning output' }).waitFor();
  assert.equal(data.task_video_winners.length, 1);
  await dialog.getByRole('button', { name: 'Close editor' }).click();
  await page.getByRole('button', { name: 'Spawn from Edited tracker creative' }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Winning file reference').selectOption('synthetic-file');
  await dialog.getByLabel('Editor brief').fill('Keep the winning concept');
  await dialog.getByRole('button', { name: 'Create 1 variations' }).click();
  await dialog.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Edit Edited tracker creative - V1', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Spawn from Edited tracker creative', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Creation type').selectOption('funnel');
  assert.equal(await dialog.getByLabel('TOF', { exact: true }).count(), 0);
  await dialog.getByRole('button', { name: 'Create missing stages' }).click();
  await dialog.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Edit Edited tracker creative - MOF', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Winning files for Edited tracker creative', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('button', { name: 'Remove Winning output' }).click();
  await dialog.getByRole('button', { name: 'Remove Winning output' }).waitFor({ state: 'detached' });
  await dialog.getByRole('button', { name: 'Close editor' }).click();
  await page.getByRole('button', { name: 'Delete Edited tracker creative', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete creative', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Edit Edited tracker creative', exact: true }).waitFor({ state: 'detached' });
  assert.equal(await page.getByRole('button', { name: 'Edit Edited tracker creative - V1', exact: true }).count(), 1);
  await page.screenshot({ path: `${artifactDir}/tracker-mobile.png`, fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: `${artifactDir}/tracker-desktop.png`, fullPage: true });
  results.push('Tracker create/edit, custom zero/boolean fields, draft preservation, inline status, winner add/remove, variations, missing funnel stages, independent deletion, desktop/mobile at /');
};
