insert into public.products(id,name,config) values('qa-mapping-fixture','Mapping fixture','{}'),('qa-mapping-foreign','Foreign mapping','{}');
insert into auth.users(id,email,raw_app_meta_data) values('00000000-0000-4000-8000-000000000244','mapping-fixture@example.test','{"must_change_password":false}');
insert into public.user_products(user_id,product_id) values('00000000-0000-4000-8000-000000000244','qa-mapping-fixture');
insert into public.inspirations(id,product_id,url,title,status,data) values('QA-MAP','qa-mapping-fixture','https://example.test/mapping','Mapping','Classified','{"angle":"Detected","persona":"Local","_needsAngleReview":true,"_needsPersonaReview":true,"notes":"keep","_clickupDocPageUrl":"https://example.test/brief","_classificationBrief":{"why_it_works":"keep"}}');
insert into public.angles(id,product_id,name) values('qa-map-angle','qa-mapping-fixture','Canonical angle'),('qa-map-foreign','qa-mapping-foreign','Foreign');
insert into public.personas(id,product_id,name,archived_at) values('qa-map-archived','qa-mapping-fixture','Archived persona',now());
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000000244","role":"authenticated"}',true);
set local role authenticated;
do $$
declare i public.inspirations%rowtype; a public.angles%rowtype; p public.personas%rowtype; payload jsonb; req uuid:=gen_random_uuid(); saved jsonb; before_version timestamptz; count_before int;
begin
 select * into i from public.inspirations where id='QA-MAP';select * into a from public.angles where id='qa-map-angle';before_version:=i.updated_at;
 payload:=jsonb_build_object('fields',jsonb_build_object('angle',a.name),'mapping',jsonb_build_object('kind','angle','mode','existing','targetId',a.id,'targetVersion',a.updated_at));
 begin perform public.qa_inspiration_mapping('qa-mapping-foreign',req,'save',i.id,i.updated_at,payload);raise exception 'FAILED access';
 exception when others then if sqlerrm<>'Active product access is required' then raise; end if; end;
 begin perform public.qa_inspiration_mapping(i.product_id,req,'save',i.id,i.updated_at,jsonb_set(payload,'{mapping,targetId}','"qa-map-foreign"'));raise exception 'FAILED foreign target';
 exception when others then if sqlerrm not like 'Taxonomy entry changed%' then raise; end if; end;
 begin perform public.qa_inspiration_mapping(i.product_id,req,'save',i.id,i.updated_at,jsonb_set(payload,'{mapping,targetVersion}','"2000-01-01"'));raise exception 'FAILED stale target';
 exception when others then if sqlerrm not like 'Taxonomy entry changed%' then raise; end if; end;
 begin perform public.qa_inspiration_mapping(i.product_id,req,'save',i.id,'2000-01-01',payload);raise exception 'FAILED stale source';
 exception when others then if sqlerrm not like 'Inspiration changed%' then raise; end if; end;
 saved:=public.qa_inspiration_mapping(i.product_id,req,'save',i.id,i.updated_at,payload);
 if saved->'row'->'data'->>'angle'<>a.name or saved->'mapping'->>'targetId'<>a.id or saved->'row'->'data'->>'_needsAngleReview'<>'false'
   or saved->'row'->'data'->>'_angleScope'<>'product' or saved->'row'->'data'->>'notes'<>'keep' or saved->'row'->'data'->'_classificationBrief'<>i.data->'_classificationBrief' then raise exception 'Mapping contract failed'; end if;
 if public.qa_inspiration_mapping(i.product_id,req,'save',i.id,before_version,payload)<>saved then raise exception 'Replay failed'; end if;
 begin perform public.qa_inspiration_mapping(i.product_id,req,'save',i.id,before_version,jsonb_set(payload,'{mapping,mode}','"custom"'));raise exception 'FAILED collision';
 exception when others then if sqlerrm<>'Request identity conflicts with a previous operation' then raise; end if; end;
 i:=jsonb_populate_record(i,saved->'row');
 select count(*) into count_before from public.personas where product_id=i.product_id;
 saved:=public.qa_inspiration_mapping(i.product_id,gen_random_uuid(),'save',i.id,i.updated_at,'{"fields":{"persona":"Custom label"},"mapping":{"kind":"persona","mode":"custom"}}');
 if saved->'mapping'->>'targetId' is not null or saved->'row'->'data'->>'_personaScope'<>'inspiration' or (select count(*) from public.personas where product_id=i.product_id)<>count_before then raise exception 'Custom label promoted'; end if;
 i:=jsonb_populate_record(i,saved->'row');
 select * into p from public.personas where id='qa-map-archived';
 payload:=jsonb_build_object('fields',jsonb_build_object('persona',p.name),'mapping',jsonb_build_object('kind','persona','mode','existing','targetId',p.id,'targetVersion',p.updated_at));
 begin perform public.qa_inspiration_mapping(i.product_id,gen_random_uuid(),'save',i.id,i.updated_at,payload);raise exception 'FAILED archived';
 exception when others then if sqlerrm not like 'Taxonomy entry changed%' then raise; end if; end;
 payload:='{"fields":{"persona":"New persona"},"mapping":{"kind":"persona","mode":"new"}}';req:=gen_random_uuid();before_version:=i.updated_at;
 saved:=public.qa_inspiration_mapping(i.product_id,req,'save',i.id,i.updated_at,payload);
 if (select count(*) from public.personas where product_id=i.product_id)<>count_before+1 or saved->'mapping'->>'targetId' is null then raise exception 'Promotion failed'; end if;
 if public.qa_inspiration_mapping(i.product_id,req,'save',i.id,before_version,payload)<>saved then raise exception 'Promotion replay failed'; end if;
 i:=jsonb_populate_record(i,saved->'row');
 begin perform public.qa_inspiration_mapping(i.product_id,gen_random_uuid(),'save',i.id,i.updated_at,jsonb_set(payload,'{fields,persona}','"NEW  PERSONA"'));raise exception 'FAILED duplicate';
 exception when others then if sqlerrm not like 'This taxonomy name already exists%' then raise; end if; end;
 begin perform public.qa_inspiration_mapping(i.product_id,gen_random_uuid(),'save',i.id,i.updated_at,jsonb_set(payload,'{fields,persona}','"Archived persona"'));raise exception 'FAILED archived resurrection';
 exception when others then if sqlerrm not like 'This taxonomy name already exists%' then raise; end if; end;
 reset role;
 if public.qa_inspiration_taxonomy_key('* 1. '||chr(8226)||' Energy'||chr(8212)||'tools')<>public.qa_inspiration_taxonomy_key('energy - tools') then raise exception 'Canonical duplicate key failed'; end if;
 insert into public.inspiration_queue(product_id,ins_id,url,status) values(i.product_id,i.id,i.url,'processing');
 select jsonb_build_object('fields','{"angle":"Blocked promotion"}'::jsonb,'mapping','{"kind":"angle","mode":"new"}'::jsonb,'queue',to_jsonb(q)) into payload from public.inspiration_queue q where ins_id=i.id;
 set local role authenticated;
 begin perform public.qa_inspiration_mapping(i.product_id,gen_random_uuid(),'save',i.id,i.updated_at,payload);raise exception 'FAILED active worker';
 exception when others then if sqlerrm not like 'Wait for the active classifier%' then raise; end if; end;
 if exists(select 1 from public.angles where product_id=i.product_id and name='Blocked promotion') then raise exception 'Failed mapping left a taxonomy row'; end if;
end $$;
reset role;
do $$ begin if has_function_privilege('anon','public.qa_inspiration_mapping(text,uuid,text,text,timestamptz,jsonb)','EXECUTE') then raise exception 'Anonymous access'; end if; end $$;
