// Vercel Serverless Function — generates a pre-filled installer for the
// /classify-inspiration skill on demand, reading secrets from Vercel env vars
// so nothing sensitive ever lives in git.
//
// Usage (what teammates paste in their Terminal):
//   curl -fsSL 'https://immuvi-command-center.vercel.app/api/install-skill?t=<secret>' | bash
//
// The `t` query param must match INSTALL_SKILL_SECRET (rotatable env var).
// If it doesn't, we return 401 and DO NOT include any credentials in the
// response body. Even the error message is safe to paste publicly.
//
// Env vars this function reads (set via `vercel env add`):
//   - INSTALL_SKILL_SECRET       : the shared "team secret"; rotate if leaked
//   - SUPABASE_SERVICE_ROLE_KEY  : piped into the teammate's ~/.classify-inspiration.env
//   - SUPABASE_DB_PASSWORD       : same
//
// The installer script it generates is identical to /team-skill/install-skill.sh
// except the two interactive `read -rs` prompts are replaced with the embedded
// values, so teammates run one line and everything installs.

export default async function handler(req, res) {
  // No caching — if creds rotate, the next curl must see fresh values.
  res.setHeader('Cache-Control', 'no-store, max-age=0');

  // Constant-time-ish token compare. Node's built-in timing-safe-equal
  // requires equal-length buffers, so we length-check first.
  const provided = (req.query && req.query.t) || '';
  const expected = process.env.INSTALL_SKILL_SECRET || '';
  if (!expected) {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.status(500).send('Installer disabled: INSTALL_SKILL_SECRET not configured.\n');
    return;
  }
  if (provided.length !== expected.length || !timingSafeEqual(provided, expected)) {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.status(401).send('Unauthorized. Contact Gaurav for the correct install link.\n');
    return;
  }

  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const dbPassword = process.env.SUPABASE_DB_PASSWORD;
  if (!serviceKey || !dbPassword) {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.status(500).send('Installer misconfigured: SUPABASE_* env vars missing on the server.\n');
    return;
  }

  // bash-safe single-quote escape (wraps the value in '...' and escapes any ')
  const sq = (s) => "'" + String(s).replace(/'/g, "'\\''") + "'";
  const SRK = sq(serviceKey);
  const DBP = sq(dbPassword);

  // Generate the installer. This is the same shape as team-skill/install-skill.sh
  // except the two `read -rs` prompts are replaced with embedded values, and the
  // "version" string includes a hash so teammates can tell when the installer
  // itself changed. We deliberately keep the script self-contained (not just a
  // thin wrapper that curls the static script) so the whole flow is one HTTP
  // round-trip — no TOCTOU window between "get script" and "get creds".
  const version = `1.1.0-prefilled`;
  const assetBase = `https://immuvi-command-center.vercel.app/team-skill`;

  const script = `#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Immuvi /classify-inspiration skill — PRE-FILLED one-line installer
# Generated by api/install-skill.js at ${new Date().toISOString()}
# Installer version: ${version}
#
# DO NOT share this URL in public channels — it contains a rotatable
# team secret in the query string. Gaurav will send it via DM only.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALLER_VERSION=${sq(version)}
ASSET_BASE=${sq(assetBase)}
SKILL_DIR="$HOME/.claude/skills/classify-inspiration"
ENV_FILE="$HOME/.classify-inspiration.env"

# Embedded credentials — only the teammate's machine will ever see them.
SUPABASE_SERVICE_ROLE_KEY=${SRK}
SUPABASE_DB_PASSWORD=${DBP}

# Colors
BOLD=$'\\e[1m'; RED=$'\\e[31m'; GRN=$'\\e[32m'; YLW=$'\\e[33m'; BLU=$'\\e[36m'; OFF=$'\\e[0m'
say()  { echo "\${BLU}▸\${OFF} $*"; }
ok()   { echo "\${GRN}✓\${OFF} $*"; }
warn() { echo "\${YLW}⚠\${OFF} $*"; }
fail() { echo "\${RED}✗\${OFF} $*"; exit 1; }

echo ""
echo "\${BOLD}Immuvi /classify-inspiration — pre-filled installer v\${INSTALLER_VERSION}\${OFF}"
echo ""
echo "Installing ~200 MB of dependencies (ffmpeg, Playwright Chromium, etc.)"
echo "and setting up your Supabase credentials. ~3 minutes."
echo ""

# ── 0. Sanity ──────────────────────────────────────────────────────────────
if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "This installer is macOS-only. You're on $(uname -s)."
fi
if ! command -v brew >/dev/null 2>&1; then
  fail "Homebrew not installed. Install it from https://brew.sh and re-run."
fi
if ! command -v python3 >/dev/null 2>&1; then
  fail "python3 not on PATH. Install via: brew install python@3.12"
fi
if ! command -v claude >/dev/null 2>&1; then
  warn "Claude Code CLI not detected. Install it before the skill can be used."
fi

# ── 1. Write env file (chmod 600) ──────────────────────────────────────────
say "Writing env file to $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<ENVEOF
# Immuvi /classify-inspiration skill — DO NOT COMMIT, DO NOT share
# Installed by the pre-filled installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SUPABASE_URL=https://hdniumnkprkadlrrataz.supabase.co
SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_DB_PASSWORD=\${SUPABASE_DB_PASSWORD}
SUPABASE_DB_URL=postgresql://postgres:\${SUPABASE_DB_PASSWORD}@db.hdniumnkprkadlrrataz.supabase.co:5432/postgres
ENVEOF
chmod 600 "$ENV_FILE"
umask 022
ok "Env written (permissions: 600)"

# ── 2. System binaries ─────────────────────────────────────────────────────
say "Installing ffmpeg + yt-dlp via Homebrew"
brew list ffmpeg >/dev/null 2>&1 || brew install ffmpeg >/dev/null
brew list yt-dlp >/dev/null 2>&1 || brew install yt-dlp >/dev/null
ok "ffmpeg $(ffmpeg -version | head -1 | awk '{print $3}'), yt-dlp $(yt-dlp --version)"

# ── 3. Python packages ─────────────────────────────────────────────────────
say "Installing Python packages (psycopg2-binary, requests, playwright)"
pip3 install -q --user --break-system-packages psycopg2-binary requests playwright 2>/dev/null \\
  || pip3 install -q --user psycopg2-binary requests playwright
ok "Python packages installed"

# ── 4. Playwright Chromium ─────────────────────────────────────────────────
say "Installing Playwright Chromium (skipped if already present)"
python3 -m playwright install chromium >/dev/null 2>&1 || {
  warn "Playwright chromium install returned non-zero. Retrying with output…"
  python3 -m playwright install chromium
}
ok "Playwright Chromium ready"

# ── 5. Download skill files ────────────────────────────────────────────────
say "Downloading skill files to $SKILL_DIR"
mkdir -p "$SKILL_DIR"
curl -fsSL "\${ASSET_BASE}/SKILL.md"            -o "$SKILL_DIR/SKILL.md"
curl -fsSL "\${ASSET_BASE}/fb_ad_classifier.py" -o "$SKILL_DIR/fb_ad_classifier.py"
ok "SKILL.md + fb_ad_classifier.py installed"

# ── 6. Smoke test against Supabase ────────────────────────────────────────
say "Running a quick smoke test against Supabase"
SMOKE_OUT=$(python3 - <<PYEOF 2>&1
import os, sys
os.environ.update(dict(line.strip().split("=", 1) for line in open("\${ENV_FILE}") if line.strip() and not line.startswith("#")))
try:
    import psycopg2
    conn = psycopg2.connect(os.environ["SUPABASE_DB_URL"], connect_timeout=10)
    cur = conn.cursor(); cur.execute("select count(*) from public.products")
    count = cur.fetchone()[0]
    cur.close(); conn.close()
    print(f"OK {count}")
except Exception as e:
    print(f"FAIL {e}")
    sys.exit(1)
PYEOF
) || true

if [[ "$SMOKE_OUT" == OK* ]]; then
  ok "Connected to Supabase — can see \${SMOKE_OUT#OK } product(s)"
else
  warn "Supabase smoke test did not pass: $SMOKE_OUT"
  warn "Re-run the installer, or DM Gaurav if it keeps failing."
fi

echo ""
echo "\${BOLD}\${GRN}🎉 Installation complete\${OFF}"
echo ""
echo "Next steps:"
echo "  1. Open Claude Code in any terminal"
echo "  2. Type \${BOLD}/classify-inspiration\${OFF}"
echo "  3. Pending URLs queued from https://immuvi-command-center.vercel.app will be picked up."
echo ""
echo "To update later (or re-run this installer): just run the same curl command."
echo "To uninstall: rm -rf $SKILL_DIR $ENV_FILE"
echo ""
`;

  res.setHeader('Content-Type', 'text/x-shellscript; charset=utf-8');
  res.status(200).send(script);
}

// Timing-safe string compare (no external deps)
function timingSafeEqual(a, b) {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  let diff = 0;
  for (let i = 0; i < ab.length; i++) diff |= ab[i] ^ bb[i];
  return diff === 0;
}
